### ISSUE TITLE
x-amz-security-token header implementation

### ISSUE THREAD

**Issue by kqvanity** [raj/imdb-apios#2]
Hi.
I wanted to thank you for this project. It really saved me so much time trying to figure out `x-amz-security-token` and `x-amzn-authorization`.
I was still wondering how did you come to realize that actual implementation of these two headers!

**Comment by raj** [comment]
Hi, thx
not sure of this libray still work
but it was a copy of `imdbpie` a python library doing the same thing.
https://pypi.org/project/imdbpie/#files

yes will need to update code

**Comment by kqvanity** [comment]
Oh okay thanks. I'll give it a go!
